n=input('Digite algo ')
print('O tipo primitivo desse valor é ',type(n))
print('É um numero? ',n.isnumeric())
print('Esta em maiúsculas? ',n.isupper())
print('É alfanumerico? ',n.isalnum())
print('Só tem espaço? ',n.isspace())
print('É alfabetico? ',n.isalpha())
print('Esta em letras minusculas? ', n.islower())
print('Está capitalizada? ', n.istitle())