nome = str(input('Informe seu nome completo:  ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiuscula: {}.'.format(nome.upper()))
print('Seu nome em minusculo: {}.'.format(nome.lower()))
print('Seu nome tem ao todo {} letras.'.format(len(nome)-nome.count(' ')))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))